/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BPaintFrames;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class LoginJFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainBoxPaint
     */
    public LoginJFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jp1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlExit = new javax.swing.JLabel();
        jlMin = new javax.swing.JLabel();
        jpl2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        User_name_tf = new javax.swing.JTextField();
        LoginBTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        password_tf = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("f1"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(560, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jp1.setBackground(new java.awt.Color(153, 51, 255));
        jp1.setForeground(new java.awt.Color(255, 255, 255));
        jp1.setPreferredSize(new java.awt.Dimension(560, 30));

        jLabel3.setBackground(new java.awt.Color(153, 51, 255));
        jLabel3.setFont(new java.awt.Font("Zurich XBlk BT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255)));
        jLabel3.setOpaque(true);

        jlExit.setFont(new java.awt.Font("Zurich XBlk BT", 0, 18)); // NOI18N
        jlExit.setForeground(new java.awt.Color(255, 255, 255));
        jlExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlExit.setText("X");
        jlExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlExitMouseClicked(evt);
            }
        });

        jlMin.setFont(new java.awt.Font("Zurich XBlk BT", 0, 18)); // NOI18N
        jlMin.setForeground(new java.awt.Color(255, 255, 255));
        jlMin.setText("-");
        jlMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jlMin)
                .addGap(18, 18, 18)
                .addComponent(jlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jlExit)
                    .addComponent(jlMin))
                .addContainerGap())
        );

        getContentPane().add(jp1);
        jp1.setBounds(0, 0, 560, 60);

        jpl2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("SquareSlab Med", 0, 24)); // NOI18N
        jLabel4.setText("Username:");

        jLabel6.setFont(new java.awt.Font("SquareSlab Med", 0, 24)); // NOI18N
        jLabel6.setText("Password:");

        User_name_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                User_name_tfMouseEntered(evt);
            }
        });

        LoginBTN.setBackground(new java.awt.Color(153, 51, 255));
        LoginBTN.setFont(new java.awt.Font("SquareSlab Med", 0, 24)); // NOI18N
        LoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        LoginBTN.setText("Login");
        LoginBTN.setAlignmentY(0.0F);
        LoginBTN.setBorder(null);
        LoginBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBTNMouseClicked(evt);
            }
        });
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SquareSlab Med", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Click Here To Create A New Account");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpl2Layout = new javax.swing.GroupLayout(jpl2);
        jpl2.setLayout(jpl2Layout);
        jpl2Layout.setHorizontalGroup(
            jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpl2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jpl2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(User_name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jpl2Layout.setVerticalGroup(
            jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpl2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_name_tf))
                .addGap(18, 18, 18)
                .addGroup(jpl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(LoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(67, 67, 67))
        );

        getContentPane().add(jpl2);
        jpl2.setBounds(0, 60, 560, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlExitMouseClicked
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jlExitMouseClicked

    private void jlMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinMouseClicked
        this.setState(JFrame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_jlMinMouseClicked

    private void User_name_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_name_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_User_name_tfMouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        RegisterJFrame rjf = new RegisterJFrame(); // TODO add your handling code here:
        rjf.setVisible(true);
        rjf.pack();
        rjf.setLocationRelativeTo(null);
        rjf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void LoginBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBTNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBTNMouseClicked

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed
        // TODO add your handling code here:
        Connection conn;
        ResultSet rs;
        int flag=0;
        PreparedStatement pst;
        String username, pass, query;
        if(evt.getSource()==LoginBTN)
        {
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/boxpaintdb?" + "user=root");
                System.out.print("Connected Successfully to boxpaintdb ...!!!");
                username=User_name_tf.getText();              
                pass=String.valueOf(password_tf.getPassword()); 
                
                if(username.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Add a USERNAME");
                    flag=1;
                }               
                else if(pass.equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Enter Password...!!!");
                    flag=1;
                }
                
                query="SELECT * FROM `register_table` WHERE `USER_NAME`=? AND `PASSWORD`=?";
                pst = conn.prepareStatement(query);
                pst.setString(1, username);
                pst.setString(2, pass);
                rs=pst.executeQuery();
                
                if(flag==0 && rs.next())
                {
                    JOptionPane.showMessageDialog(null,"Login Successful .. Click OK to continue..");
                    MainBox123 mb=new MainBox123();
                    mb.setVisible(true);
                    mb.pack();
                    mb.setLocationRelativeTo(null);
                    mb.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }  
                else if(flag==0)
                {
                    JOptionPane.showMessageDialog(null,"Please Enter Valid Details...!!!");
                }                
            } 
            catch(ClassNotFoundException | NumberFormatException | SQLException e)
            {
                System.out.println(e);
            }
        } 
    }//GEN-LAST:event_LoginBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBTN;
    private javax.swing.JTextField User_name_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlExit;
    private javax.swing.JLabel jlMin;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jpl2;
    private javax.swing.JPasswordField password_tf;
    // End of variables declaration//GEN-END:variables
}
